### ISSUE TITLE
Incompatible with the EE InnerVariationBundle

### ISSUE THREAD

**Issue by ikwattro** [akeneo/ExtendedAttributeTypeBundle#10]
Hi,

first of all thanks for this bundle, it is a great source for customizing Akeneo.

Installed it on a fresh EE 1.6.7 version along with the InnerVariationBundle.

I created a Text Collection attribute.

![screen shot 2016-12-30 at 23 18 13](https://cloud.githubusercontent.com/assets/1222009/21573691/c6daa038-cee7-11e6-899a-788d6b8f8789.png)

And my variation family contains this attribute.

![screen shot 2016-12-30 at 23 19 09](https://cloud.githubusercontent.com/assets/1222009/21573694/d27c03b4-cee7-11e6-9a94-a006f0af0cf2.png)

When I edit a variation and adds items to the text collection field, it is fine

![screen shot 2016-12-30 at 23 20 28](https://cloud.githubusercontent.com/assets/1222009/21573700/e304aba0-cee7-11e6-9a63-980ba34c284a.png)

 however I cannot save the product

![screen shot 2016-12-30 at 23 20 40](https://cloud.githubusercontent.com/assets/1222009/21573704/edfb7368-cee7-11e6-81f7-7fbc901fa8f2.png)

message in the browser console : 

```json
{"values":[{"global":true,"message":"The family of this product cannot be changed because it is a variation product"}]}
```

This message is actually triggered by the `ImmutableFamilyValidator` from the InnerVariationBundle

What is strange it is that when using this custom attribute type (or any other custom attribute type), the `innerVariationRepository` checks for a `family_id` key in the mongo document and there isn't, but well a `family` key.

If I try to modify the `InnerVariationBundle` to use this key instead, then it can be saved.

**Comment by ikwattro** [comment]
NB: The behavior is exactly the same with the `RangeTypeAttribute`

**Comment by ikwattro** [comment]
Seems like it is an issue with the InnerVariationBundle. I reported it on our board. Will close it once confirmed by the Akeneo support team.

**Comment by jmleroux** [comment]
Hi @ikwattro 

Thanks for your interest in this extension. (still WIP by the way)
I also think it's more a InnerVariation bundle related issue and we will investigate on it.

Regads,
JM

**Comment by jmleroux** [comment]
Your fix proposition for the IVB bug seems to be the right one.
I'll test it and merge.
Thx ! :+1:

**Comment by jmleroux** [comment]
Hello @ikwattro ,

I just released IVB v1.3.14 to fix this issue. Let me know if i can close this issue.

Regards,
JM

**Comment by ikwattro** [comment]
Thanks, we're running the patch (by overriding the inner variation repository class in the container) since 2 days now on our 3 environments.

I'll be able to update our dependencies tomorrow and report to you.

Thanks.

**Comment by ikwattro** [comment]
@jmleroux I confirm that IVB 1.3.14 fixes the issue (well not surprising because it is exactly the workaround I proposed). Just sad that no tests were added on an `Enterprise` feature.
