### ISSUE TITLE
problem with the alignment of the attribute type window

### ISSUE THREAD

**Issue by userz58** [akeneo/ExtendedAttributeTypeBundle#11]
mac book 13 retina
1280x800
chrome

![2017-01-03 16 02 06](https://cloud.githubusercontent.com/assets/2612186/21608593/8074a6e0-d1ce-11e6-9265-ec5c1a0304b5.png)

**Comment by jmleroux** [comment]
Hi @userz58 ,
Could you explain your problem. I don't see any alignment problem.

thx,
JM

**Comment by userz58** [comment]
in the pop-up window, the bottom row of icons is hidden
need to fix the vertical alignment of pop-up window

**Comment by jmleroux** [comment]
Oh, ok
:scream: you're right
I'll check if we have screen resolution requirements in the PIM to see how we can fix.

Thx for raising this issue

Regards,
JM

**Comment by jmleroux** [comment]
By the way, this is a PIM issue that will not be fixed in this extension and i think you should raise a ticket (or even better, send a PR) on [pim-community-dev](https://github.com/akeneo/pim-community-dev) with a link to this ticket.

**Comment by pierallard** [comment]
Hi @userz58 !
We are currently refactor the entire CSS of the application!
In this PR, you will find how to avoid this behavior
https://github.com/akeneo/pim-community-dev/pull/5437/commits/ac7681ff0584e8e39e9bc63f2c5d1963af2c4f7c#diff-e04ac36dfab5421fc8cbd2205fb55029R7

Simply add `top: 50%; transform: translate(0, -50%);` on the `.modal` CSS selector, that will do the job.

You can add this line too for the huge modals (column selector e.g.)
https://github.com/akeneo/pim-community-dev/pull/5437/commits/ac7681ff0584e8e39e9bc63f2c5d1963af2c4f7c#diff-e04ac36dfab5421fc8cbd2205fb55029R50

Keep us informed ;)

Regards

**Comment by jmleroux** [comment]
I may have been wrong in my previous answer then: this extension must be compliant with the PIM minimal requirements. In this case, I will check how to fix it in this extension for the PIM 1.6 compatible branch.

**Comment by jmleroux** [comment]
fixed in https://github.com/akeneo/ExtendedAttributeTypeBundle/pull/14/commits/2c99a3f925ac3b7dd788983789ee908d3e6778ec
