### ISSUE TITLE
TextCollectionFilter wrong reference to TextCollectionFilterType

### ISSUE THREAD

**Issue by mathewrapid** [akeneo/ExtendedAttributeTypeBundle#24]
https://github.com/akeneo/ExtendedAttributeTypeBundle/blob/master/src/Filter/ProductValue/TextCollectionFilter.php#L7

should be `use Pim\Bundle\ExtendedAttributeTypeBundle\DataGrid\Form\Type\Filter\TextCollectionFilterType;` instead?

**Comment by jmleroux** [comment]
Yes, of course!
Thanks for being the first to raise an issue on this repo :)
And it shows that i have a hole in my tests. Thx again.

**Comment by jmleroux** [comment]
fixed in #23 

https://github.com/akeneo/ExtendedAttributeTypeBundle/pull/23/files#diff-17ed940dcb64dbd15dc1076ccba54c0b
