### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by userz58** [akeneo/ExtendedAttributeTypeBundle#8]
Akeneo CE 1.6.6
php app/console doctrine:schema:update --force

  [Doctrine\ORM\Mapping\MappingException]
  The target-entity PimEnterprise\Component\Workflow\Model\PublishedProductValueInterface cannot be found in 'Pim\Bundle\ExtendedAttributeTypeBundle\Model\PublishedProductRange#value'.

**Comment by jmleroux** [comment]
Oh yeah, we're not stable yet and already somenone wishing to use this bundle :+1: :)
Thanks for this issue, we will investigate on it.

**Comment by jmleroux** [comment]
It should be fixed by #9
